name: Acceptance Smoke (Planning Hub)

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Launch app (background)
        env:
          SCPLN_DB: scpln.db
          REGISTRY_BACKEND: db
          RUNS_DB_MAX_ROWS: '500'
          AUTH_MODE: 'none'
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          echo $! > server.pid
          tries=0
          until curl -sfS http://127.0.0.1:8000/healthz >/dev/null; do
            tries=$((tries+1))
            if [ $tries -gt 60 ]; then
              echo 'Server did not become healthy in time' >&2
              tail -n 200 server.log || true
              exit 1
            fi
            sleep 1
          done

      - name: Run acceptance smoke
        env:
          SCPLN_DB: scpln.db
        run: |
          python scripts/acceptance_smoke.py --base-url http://127.0.0.1:8000

      - name: Show server log on failure
        if: failure()
        run: |
          echo '==== server.log (tail) ===='
          tail -n 400 server.log || true

      - name: Upload server log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log

