name: Autofix on PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-autofix:
    if: >-
      ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/autofix') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            });
            const sameRepo = pr.data.head.repo.full_name === `${context.repo.owner}/${context.repo.repo}`;
            core.setOutput('head_ref', pr.data.head.ref);
            core.setOutput('head_repo', pr.data.head.repo.full_name);
            core.setOutput('same_repo', sameRepo ? 'true' : 'false');
            core.setOutput('pr_number', pr.data.number.toString());

      - name: Checkout PR head
        if: steps.pr.outputs.same_repo == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_ref }}
          fetch-depth: 0

      - name: Setup Python
        if: steps.pr.outputs.same_repo == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install autofix tools
        if: steps.pr.outputs.same_repo == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Apply autofixes
        if: steps.pr.outputs.same_repo == 'true'
        run: |
          ruff check --fix . || true
          black . || true

      - name: Commit and push changes
        if: steps.pr.outputs.same_repo == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(autofix): apply ruff --fix and black via /autofix"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment result
        if: steps.pr.outputs.same_repo == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pushed = process.env.pushed === 'true';
            const body = pushed ? '🧹 Applied autofix and pushed to PR branch.' : 'ℹ️ No changes needed by autofix.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(`${{ steps.pr.outputs.pr_number }}`),
              body,
            });

      - name: Fork PR notice
        if: steps.pr.outputs.same_repo != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(`${{ steps.pr.outputs.pr_number }}`),
              body: '⚠️ /autofix cannot push to forked PRs. Please pull changes locally or allow maintainers to edit the forked branch.'
            });

