name: CI Auto Retry (once)

on:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]

permissions:
  actions: write
  contents: read

jobs:
  retry:
    if: >-
      ${{ github.event.workflow_run.conclusion != 'success' && github.event.workflow_run.run_attempt == 1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Re-run failed CI once
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            core.info(`Triggered re-run for CI run_id=${context.payload.workflow_run.id}`);

