name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Install test reporter (xml)
        run: |
          pip install unittest-xml-reporting

      - name: Run tests with coverage and produce reports
        run: |
          coverage run -m scripts.run_tests_xml
          coverage xml -o coverage.xml
          coverage html -d htmlcov

      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.xml
          comment_mode: always
          check_name: Unit Test Results

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.xml
            htmlcov
          if-no-files-found: warn

      - name: Comment PR with coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            let percent = null;
            try {
              const xml = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'coverage.xml'), 'utf8');
              const m = xml.match(/<coverage[^>]*?line-rate="([0-9.]+)"/);
              if (m) percent = Math.round(parseFloat(m[1]) * 1000) / 10; // one decimal
            } catch (e) { percent = null; }
            const number = context.payload.pull_request.number;
            const body = percent == null
              ? '📊 Coverage: could not compute.'
              : `📊 Coverage: ${percent}% (line-rate).`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body
            });

      - name: Comment PR with result
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = "${{ job.status }}";
            const number = context.payload.pull_request.number;
            const summary = conclusion === 'success' ? '✅ CI passed' : `❌ CI ${conclusion}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: `${summary} (workflow: CI)`
            });
