name: Deploy to Render on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Render API (preferred)
        if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -euo pipefail
          echo "Triggering deploy for service $RENDER_SERVICE_ID via Render API"
          curl -fsS \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -X POST \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -d '{"clearCache":false}'

      - name: Trigger via Deploy Hook (fallback)
        if: ${{ !secrets.RENDER_API_KEY || !secrets.RENDER_SERVICE_ID }}
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          set -euo pipefail
          if [ -z "${RENDER_DEPLOY_HOOK_URL:-}" ]; then
            echo "Missing secret RENDER_DEPLOY_HOOK_URL or (RENDER_API_KEY & RENDER_SERVICE_ID)." >&2
            exit 1
          fi
          echo "Triggering deploy via Deploy Hook"
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"

