name: Label PR (manual)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        required: true
      labels:
        description: "Comma separated labels"
        required: true

permissions:
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_TOKEN || github.token }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr = Number(core.getInput('pr_number'));
            const labels = core.getInput('labels').split(',').map(s => s.trim()).filter(Boolean);
            // ensure labels exist; create if missing
            for (const lbl of labels) {
              try { await github.rest.issues.getLabel({ owner, repo, name: lbl }); }
              catch (e) { try { await github.rest.issues.createLabel({ owner, repo, name: lbl, color: '0E8A16' }); } catch (e2) { core.warning(`Could not create label ${lbl}: ${e2.message}`);} }
            }
            await github.rest.issues.addLabels({ owner, repo, issue_number: pr, labels });
            core.info(`Added labels to PR #${pr}: ${labels.join(', ')}`);

