name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    env:
      SCPLN_DB: ${{ runner.temp }}/test.db # 一時的なデータベースファイル
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create data directory (if needed for alembic)
        run: mkdir -p data # alembic.iniのパスが相対パスの場合に備えて残す

      - name: Run alembic migrations
        run: alembic upgrade head

      - name: Run all tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q
      - name: Clean up test database
        if: always()
        run: rm -f ${{ runner.temp }}/test.db
