name: Type Check (Optional)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_BACKEND: db
      RUNS_DB_MAX_ROWS: 1000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mypy and stubs
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-requests types-setuptools

      - name: Run mypy (non-blocking)
        run: |
          set +e
          mypy --ignore-missing-imports .
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          set -e
